Selenium advanced homework
EvgeniiSmirnov/AQA_MTS pull request #15
Opened 2024-02-11 18:43 UTC by EvgeniiSmirnov

2024-02-12 21:10 UTC, wildpioneer requested changes

2024-02-12 21:10 UTC, wildpioneer commented on SeleniumLocators/Tests/HomeworkTests.cs
> +            Assert.That(input.Enabled, Is.False);
Тут можно использовать инверсию через !

2024-02-12 21:10 UTC, wildpioneer commented on SeleniumLocators/Helpers/WaitsHelper.cs
> +        do
Немного странный вариант - но рабочий. Я бы хотел, чтобы ты это реализовал через wait.Until с использованием лямбда выражения

2024-02-13 15:37 UTC, EvgeniiSmirnov commented on SeleniumLocators/Tests/HomeworkTests.cs
> +            Assert.That(input.Enabled, Is.False);
исправил

2024-02-13 15:37 UTC, EvgeniiSmirnov commented on SeleniumLocators/Helpers/WaitsHelper.cs
> +        do
исправил

2024-02-13 15:38 UTC, merged